/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author Cassiano
 */
public class JFDepositar extends javax.swing.JFrame {

    /**
     * Creates new form JFDepositar
     */
    public JFDepositar() {
        initComponents();
    }
    public int n;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NumeroD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        saldin = new javax.swing.JLabel();
        pesquisaD = new javax.swing.JButton();
        Deposita = new javax.swing.JTextField();
        Okd = new javax.swing.JButton();
        limm = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("N° Conta ");

        NumeroD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroDActionPerformed(evt);
            }
        });

        jLabel2.setText("Depositar");

        jLabel4.setText("Saldo");

        saldin.setAlignmentX(6.0F);

        pesquisaD.setText("Pesquisar");
        pesquisaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaDActionPerformed(evt);
            }
        });

        Deposita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositaActionPerformed(evt);
            }
        });

        Okd.setText("Ok");
        Okd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkdActionPerformed(evt);
            }
        });

        limm.setText("Limpar");
        limm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limmActionPerformed(evt);
            }
        });

        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(NumeroD, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesquisaD)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saldin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Okd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limm, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Deposita, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NumeroD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisaD)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Deposita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Okd)
                    .addComponent(limm)
                    .addComponent(cancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeroDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroDActionPerformed

    }//GEN-LAST:event_NumeroDActionPerformed

    private void pesquisaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaDActionPerformed
        String str = NumeroD.getText();
        int istr = Integer.parseInt(str);
        if(Principal.conta1.getNumero()==istr){
            String str1 = String.valueOf(Principal.conta1.getSaldo());
            saldin.setText(str1);
            n=1;
            //tipoN(n);
        }
        if(Principal.conta2.getNumero()==istr){
            String str2 = String.valueOf(Principal.conta2.getSaldo());
            saldin.setText(str2);
            n=2;
            //tipoN(n);
        }
        if(Principal.conta3.getNumero()==istr){
            String str3 = String.valueOf(Principal.conta3.getSaldo());
            saldin.setText(str3);
            n=3;
            //tipoN(n);
        }
    }//GEN-LAST:event_pesquisaDActionPerformed

    private void DepositaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepositaActionPerformed

    private void OkdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkdActionPerformed
        String strSaque = Deposita.getText();
        double dbSaque = Double.parseDouble(strSaque);
        int response = JOptionPane.showConfirmDialog(this, "Deseja continuar?", "Confirmar" , JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_NO_OPTION){
            if(n==1){
            JOptionPane.showMessageDialog(null, "Deposito efetuado com sucesso", Principal.conta1.getNome(), 1);
            Principal.conta1.depositar(dbSaque);
            Principal.conta1.getNome();
            JFInicial inicio = new JFInicial();
            inicio.setResizable(false);
            inicio.setVisible(true);
            dispose();
            
        }else if(n==2){
            JOptionPane.showMessageDialog(null, "Depostio efetuado com sucesso", Principal.conta2.getNome(), 1);
            Principal.conta2.depositar(dbSaque);
            JFInicial inicio = new JFInicial();
            inicio.setResizable(false);
            inicio.setVisible(true);
            dispose();
           
        } else if(n==3){
            JOptionPane.showMessageDialog(null, "Depostio efetuado com sucesso", Principal.conta3.getNome(), 1);
            Principal.conta3.depositar(dbSaque);
            JFInicial inicio = new JFInicial();
            inicio.setResizable(false);
            inicio.setVisible(true);
            dispose();
            
        }
        }else if(response==JOptionPane.CANCEL_OPTION){
            dispose();
            JFDepositar d = new JFDepositar();
            d.setResizable(false);
            d.setVisible(true);
            JOptionPane.showMessageDialog(null, "Deposito cancelado");
        }else if(response==JOptionPane.NO_OPTION){
            dispose();
            JFDepositar d = new JFDepositar();
            d.setResizable(false);
            d.setVisible(true);
            JOptionPane.showMessageDialog(null, "Operação não realizada");
        }
        
    }//GEN-LAST:event_OkdActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       JFInicial inicio = new JFInicial();
        inicio.setVisible(true);
        inicio.setResizable(false);
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void limmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limmActionPerformed
        NumeroD.setText("");
        Deposita.setText("");
    }//GEN-LAST:event_limmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDepositar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Deposita;
    private javax.swing.JTextField NumeroD;
    private javax.swing.JButton Okd;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limm;
    private javax.swing.JButton pesquisaD;
    private javax.swing.JLabel saldin;
    // End of variables declaration//GEN-END:variables
}
