/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author Cassiano
 */
public class JFTrans extends javax.swing.JFrame {

    /**
     * Creates new form JFr
     */
    public JFTrans() {
        initComponents();
    }
   
    public int n1, n2;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        num1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        saldo1 = new javax.swing.JLabel();
        pesquisa1 = new javax.swing.JButton();
        Trans = new javax.swing.JTextField();
        limm = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        num2 = new javax.swing.JTextField();
        pesquisa2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        saldo2 = new javax.swing.JLabel();
        Okd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("N° Conta ");

        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Transferir");

        jLabel4.setText("Saldo");

        saldo1.setAlignmentX(6.0F);

        pesquisa1.setText("Pesquisar");
        pesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa1ActionPerformed(evt);
            }
        });

        Trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransActionPerformed(evt);
            }
        });

        limm.setText("Limpar");
        limm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limmActionPerformed(evt);
            }
        });

        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel3.setText("N° Conta ");

        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        pesquisa2.setText("Pesquisar");
        pesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Saldo");

        saldo2.setAlignmentX(6.0F);

        Okd.setText("Ok");
        Okd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Trans, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesquisa1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesquisa2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Okd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limm, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Trans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Okd)
                    .addComponent(limm)
                    .addComponent(cancel))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed

    }//GEN-LAST:event_num1ActionPerformed

    private void pesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa1ActionPerformed
        String str = num1.getText();
        int istr = Integer.parseInt(str);
        if(Principal.conta1.getNumero()==istr){
            String str1 = String.valueOf(Principal.conta1.getSaldo());
            saldo1.setText(str1);
            n1=1;
          
        }
        if(Principal.conta2.getNumero()==istr){
            String str2 = String.valueOf(Principal.conta2.getSaldo());
            saldo1.setText(str2);
            n1=2;
          
        }
        if(Principal.conta3.getNumero()==istr){
            String str3 = String.valueOf(Principal.conta3.getSaldo());
            saldo1.setText(str3);
            n1=3;
      
        }
    }//GEN-LAST:event_pesquisa1ActionPerformed

    private void TransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransActionPerformed

    private void OkdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkdActionPerformed
        String strSaque = Trans.getText();
        double dbSaque = Double.parseDouble(strSaque);
        int response = JOptionPane.showConfirmDialog(this, "Deseja continuar?", "Confirmar" , JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(response==JOptionPane.YES_NO_OPTION){
            if(n1==1){
            JOptionPane.showMessageDialog(null, "Saque efetuado.. ", Principal.conta1.getNome(), 1);
            Principal.conta1.sacar(dbSaque);
            
        }else if(n1==2){
            JOptionPane.showMessageDialog(null, "Saque efetuado..", Principal.conta2.getNome(), 1);
            Principal.conta2.sacar(dbSaque);
            
        } else if(n1==3){
            JOptionPane.showMessageDialog(null, "Saque efetuado..", Principal.conta3.getNome(), 1);
            Principal.conta3.descontar(dbSaque, Principal.conta3.getSaldo(),Principal.conta3.getLimite(),Principal.conta3.getMulta());
            
        }
        if(n2==1){
            JOptionPane.showMessageDialog(null, "Deposito efetuado..", Principal.conta1.getNome(), 1);
            Principal.conta1.depositar(dbSaque);
            
          
        }else if(n2==2){
            JOptionPane.showMessageDialog(null, "Deposito efetuado..", Principal.conta2.getNome(), 1);
            Principal.conta2.depositar(dbSaque);
           
        }else if(n2==3){
            JOptionPane.showMessageDialog(null, "Deposito efetuado..", Principal.conta3.getNome(), 1);
            Principal.conta3.depositar(dbSaque);
            
        }
        JFInicial inicio = new JFInicial();
        inicio.setResizable(false);
        inicio.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(null, "Transferência efetuada com sucesso!");
            
        }else if(response==JOptionPane.CANCEL_OPTION){
            dispose();
            JFInicial inicio = new JFInicial();
            inicio.setResizable(false);
            inicio.setVisible(true);
            JOptionPane.showMessageDialog(null, "Transferência não realizada");
        }else if(response==JOptionPane.NO_OPTION){
            dispose();
            JFInicial inicio = new JFInicial();
            inicio.setResizable(false);
            inicio.setVisible(true);
            JOptionPane.showMessageDialog(null, "Operação não realizada");
        }
        
        
    }//GEN-LAST:event_OkdActionPerformed

    private void limmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limmActionPerformed
        num1.setText("");
        num2.setText("");
        Trans.setText("");
    }//GEN-LAST:event_limmActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        JFInicial inicio = new JFInicial();
        inicio.setVisible(true);
        inicio.setResizable(false);
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num2ActionPerformed

    private void pesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa2ActionPerformed
         String str = num2.getText();
        int istr = Integer.parseInt(str);
        if(Principal.conta1.getNumero()==istr){
            String str1 = String.valueOf(Principal.conta1.getSaldo());
            saldo2.setText(str1);
            n2=1;
            
        }
        if(Principal.conta2.getNumero()==istr){
            String str2 = String.valueOf(Principal.conta2.getSaldo());
            saldo2.setText(str2);
            n2=2;
           
        }
        if(Principal.conta3.getNumero()==istr){
            String str3 = String.valueOf(Principal.conta3.getSaldo());
            saldo2.setText(str3);
            n2=3;
            
        }
    }//GEN-LAST:event_pesquisa2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTrans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Okd;
    private javax.swing.JTextField Trans;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limm;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JButton pesquisa1;
    private javax.swing.JButton pesquisa2;
    private javax.swing.JLabel saldo1;
    private javax.swing.JLabel saldo2;
    // End of variables declaration//GEN-END:variables
}
